### ISSUE TITLE
Paystack popup is not showing

### ISSUE THREAD

**Issue by Nikitajain1121** [Akinnagbe/PaystackInline.Forms.Plugin#2]
Run the sample , but unable to get the Paystack popup
Like refer the image attached:
![New-Paystack-Checkout-Form](https://user-images.githubusercontent.com/35139605/61538008-1fdd0a80-aa56-11e9-878a-7a0e344e5ca8.jpg)

Getting this error when build : 
chromium] [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'getItem' of null", source: https://checkout.paystack.com/static/js/app.c234a5b6a8f08780bf07.js (1)
[chromium] [INFO:CONSOLE(28)] "Error during service worker registration:", source: https://checkout.paystack.com/popup (28)

**Comment by Akinnagbe** [comment]
@Nikitajain1121 please what version of Xamarin Forms are you using?

Thanks

**Comment by Nikitajain1121** [comment]
Hello,
I m using xamarin form latest version 4.1.0

**Comment by onojaheron-amos** [comment]
Mine is not showing error but not piping out at all

**Comment by Nikitajain1121** [comment]
Hello,
Actually, the error is showing in Application output at runtime.
Did you find any solution?

Thanks and Regards,
*Nikita Jain*

**Comment by Akinnagbe** [comment]
Dear All, 

Thanks for the feedback, this issue is now fixed. Meanwhile, you will need to create a model class as against using dynamic data/Json JObject

Please update the package to 2.0.0 (the stable version)

**Comment by onlinespec** [comment]
Good day. Please how do I implement Apple Pay.

**Comment by Akinnagbe** [comment]
Hi onlinespec,

I am sorry, the plugin does not support Apple but since you want to
implement it, you can do direct binding i.e. using Xamarin Android and iOS
bindings to port the SDK to Xamarin.

Regards.
